// ------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version: 10.0.0.0
//  
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
// ------------------------------------------------------------------------------
namespace VHDLCompiler.CodeTemplates.Types
{
    using System;
    
    
    #line 1 "C:\Users\Denis\Desktop\Compiler\VHDLCompiler\CodeTemplates\Types\PhysicalTypeTemplate.tt"
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.TextTemplating", "10.0.0.0")]
    public partial class PhysicalTypeTemplate : PhysicalTypeTemplateBase
    {
        public virtual string TransformText()
        {
            this.Write("using System;\r\nusing VHDLRuntime;\r\nusing VHDLRuntime.Types;\r\nusing VHDLRuntime.Ra" +
                    "nge;\r\nusing VHDLRuntime.Values;\r\n\r\nnamespace ");
            
            #line 8 "C:\Users\Denis\Desktop\Compiler\VHDLCompiler\CodeTemplates\Types\PhysicalTypeTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(NameSpaceName));
            
            #line default
            #line hidden
            this.Write("\r\n{\r\n    [Serializable]\r\n    public class ");
            
            #line 11 "C:\Users\Denis\Desktop\Compiler\VHDLCompiler\CodeTemplates\Types\PhysicalTypeTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Name));
            
            #line default
            #line hidden
            this.Write("_PhysicalValue : PhysicalUnitBaseType<");
            
            #line 11 "C:\Users\Denis\Desktop\Compiler\VHDLCompiler\CodeTemplates\Types\PhysicalTypeTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Name));
            
            #line default
            #line hidden
            this.Write("_PhysicalValue>\r\n    {\r\n\t\t");
            
            #line 13 "C:\Users\Denis\Desktop\Compiler\VHDLCompiler\CodeTemplates\Types\PhysicalTypeTemplate.tt"
 foreach (var item in dict) 
		// Items that declared in type definition
		{ 
            
            #line default
            #line hidden
            this.Write("\t\t\tpublic static ");
            
            #line 16 "C:\Users\Denis\Desktop\Compiler\VHDLCompiler\CodeTemplates\Types\PhysicalTypeTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Name));
            
            #line default
            #line hidden
            this.Write("_PhysicalValue ");
            
            #line 16 "C:\Users\Denis\Desktop\Compiler\VHDLCompiler\CodeTemplates\Types\PhysicalTypeTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(item.UnitName));
            
            #line default
            #line hidden
            this.Write(";\r\n\t\t");
            
            #line 17 "C:\Users\Denis\Desktop\Compiler\VHDLCompiler\CodeTemplates\Types\PhysicalTypeTemplate.tt"
 } // end of foreach 
            
            #line default
            #line hidden
            this.Write("\r\n\r\n        static ");
            
            #line 20 "C:\Users\Denis\Desktop\Compiler\VHDLCompiler\CodeTemplates\Types\PhysicalTypeTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Name));
            
            #line default
            #line hidden
            this.Write("_PhysicalValue()\r\n        {\r\n            TIME_PhysicalValue.Init();\r\n        }\r\n\r" +
                    "\n        public ");
            
            #line 25 "C:\Users\Denis\Desktop\Compiler\VHDLCompiler\CodeTemplates\Types\PhysicalTypeTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Name));
            
            #line default
            #line hidden
            this.Write("_PhysicalValue(long multiplier, string unitName)\r\n            : base(multiplier, " +
                    "unitName)\r\n        {\r\n        }\r\n\r\n        public ");
            
            #line 30 "C:\Users\Denis\Desktop\Compiler\VHDLCompiler\CodeTemplates\Types\PhysicalTypeTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Name));
            
            #line default
            #line hidden
            this.Write("_PhysicalValue(long multiplier, string unitName, string baseUnitName)\r\n          " +
                    "  : base(multiplier, unitName, baseUnitName)\r\n        {\r\n        }\r\n\r\n        pu" +
                    "blic static void Init()\r\n        {\r\n\t\t\t");
            
            #line 37 "C:\Users\Denis\Desktop\Compiler\VHDLCompiler\CodeTemplates\Types\PhysicalTypeTemplate.tt"
 foreach (var item in dict) 
			// Items that declared in type definition
			{ 
            
            #line default
            #line hidden
            this.Write("\t\t\t\tif (");
            
            #line 40 "C:\Users\Denis\Desktop\Compiler\VHDLCompiler\CodeTemplates\Types\PhysicalTypeTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(item.UnitName));
            
            #line default
            #line hidden
            this.Write(" == null)\r\n\t\t\t\t{\r\n\t\t\t\t\t");
            
            #line 42 "C:\Users\Denis\Desktop\Compiler\VHDLCompiler\CodeTemplates\Types\PhysicalTypeTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(item.UnitName));
            
            #line default
            #line hidden
            this.Write(" = new TIME_PhysicalValue(");
            
            #line 42 "C:\Users\Denis\Desktop\Compiler\VHDLCompiler\CodeTemplates\Types\PhysicalTypeTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(item.Multiplier.ToString()));
            
            #line default
            #line hidden
            this.Write(", \"");
            
            #line 42 "C:\Users\Denis\Desktop\Compiler\VHDLCompiler\CodeTemplates\Types\PhysicalTypeTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(item.UnitName));
            
            #line default
            #line hidden
            this.Write("\", \"");
            
            #line 42 "C:\Users\Denis\Desktop\Compiler\VHDLCompiler\CodeTemplates\Types\PhysicalTypeTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(item.BaseUnitName));
            
            #line default
            #line hidden
            this.Write("\");\r\n\t\t\t\t}\r\n\t\t\t");
            
            #line 44 "C:\Users\Denis\Desktop\Compiler\VHDLCompiler\CodeTemplates\Types\PhysicalTypeTemplate.tt"
 } // end of foreach 
            
            #line default
            #line hidden
            this.Write("            \r\n        }\r\n    }\r\n\r\n\r\n\r\n    public class ");
            
            #line 50 "C:\Users\Denis\Desktop\Compiler\VHDLCompiler\CodeTemplates\Types\PhysicalTypeTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Name));
            
            #line default
            #line hidden
            this.Write(" : VHDLPhysicalValue<");
            
            #line 50 "C:\Users\Denis\Desktop\Compiler\VHDLCompiler\CodeTemplates\Types\PhysicalTypeTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Name));
            
            #line default
            #line hidden
            this.Write("_PhysicalValue>\r\n    {\r\n        private static VHDLPhysicalType<");
            
            #line 52 "C:\Users\Denis\Desktop\Compiler\VHDLCompiler\CodeTemplates\Types\PhysicalTypeTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Name));
            
            #line default
            #line hidden
            this.Write("_PhysicalValue> physType;\r\n\r\n        public static VHDLPhysicalType<");
            
            #line 54 "C:\Users\Denis\Desktop\Compiler\VHDLCompiler\CodeTemplates\Types\PhysicalTypeTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Name));
            
            #line default
            #line hidden
            this.Write("_PhysicalValue> PhysType\r\n        {\r\n            get\r\n            {\r\n            " +
                    "    if (physType == null)\r\n                {\r\n                    physType = new" +
                    " VHDLPhysicalType<");
            
            #line 60 "C:\Users\Denis\Desktop\Compiler\VHDLCompiler\CodeTemplates\Types\PhysicalTypeTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Name));
            
            #line default
            #line hidden
            this.Write("_PhysicalValue>(");
            
            #line 60 "C:\Users\Denis\Desktop\Compiler\VHDLCompiler\CodeTemplates\Types\PhysicalTypeTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(RangeLeft));
            
            #line default
            #line hidden
            this.Write(", ");
            
            #line 60 "C:\Users\Denis\Desktop\Compiler\VHDLCompiler\CodeTemplates\Types\PhysicalTypeTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(RangeRight));
            
            #line default
            #line hidden
            this.Write(", ");
            
            #line 60 "C:\Users\Denis\Desktop\Compiler\VHDLCompiler\CodeTemplates\Types\PhysicalTypeTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Direction));
            
            #line default
            #line hidden
            this.Write(");\r\n                }\r\n                return physType;\r\n            }\r\n        }" +
                    "\r\n\r\n        static ");
            
            #line 66 "C:\Users\Denis\Desktop\Compiler\VHDLCompiler\CodeTemplates\Types\PhysicalTypeTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Name));
            
            #line default
            #line hidden
            this.Write("()\r\n        {\r\n            ");
            
            #line 68 "C:\Users\Denis\Desktop\Compiler\VHDLCompiler\CodeTemplates\Types\PhysicalTypeTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Name));
            
            #line default
            #line hidden
            this.Write("_PhysicalValue.Init();\r\n        }\r\n\r\n        public ");
            
            #line 71 "C:\Users\Denis\Desktop\Compiler\VHDLCompiler\CodeTemplates\Types\PhysicalTypeTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Name));
            
            #line default
            #line hidden
            this.Write("(long value, string unitName)\r\n            : base(PhysType, value, unitName)\r\n   " +
                    "     {\r\n        }\r\n\r\n        public ");
            
            #line 76 "C:\Users\Denis\Desktop\Compiler\VHDLCompiler\CodeTemplates\Types\PhysicalTypeTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Name));
            
            #line default
            #line hidden
            this.Write("()\r\n            : base(PhysType)\r\n        {\r\n        }\r\n\r\n        public ");
            
            #line 81 "C:\Users\Denis\Desktop\Compiler\VHDLCompiler\CodeTemplates\Types\PhysicalTypeTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Name));
            
            #line default
            #line hidden
            this.Write("(long value)\r\n            : base(PhysType, value)\r\n        {\r\n        }\r\n\r\n      " +
                    "  public ");
            
            #line 86 "C:\Users\Denis\Desktop\Compiler\VHDLCompiler\CodeTemplates\Types\PhysicalTypeTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Name));
            
            #line default
            #line hidden
            this.Write("(VHDLPhysicalValue<");
            
            #line 86 "C:\Users\Denis\Desktop\Compiler\VHDLCompiler\CodeTemplates\Types\PhysicalTypeTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Name));
            
            #line default
            #line hidden
            this.Write("_PhysicalValue> value)\r\n            : base(PhysType, value)\r\n        {\r\n        }" +
                    "\r\n    }\r\n}");
            return this.GenerationEnvironment.ToString();
        }
    }
    
    #line default
    #line hidden
    #region Base class
    /// <summary>
    /// Base class for this transformation
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.TextTemplating", "10.0.0.0")]
    public class PhysicalTypeTemplateBase
    {
        #region Fields
        private global::System.Text.StringBuilder generationEnvironmentField;
        private global::System.CodeDom.Compiler.CompilerErrorCollection errorsField;
        private global::System.Collections.Generic.List<int> indentLengthsField;
        private string currentIndentField = "";
        private bool endsWithNewline;
        private global::System.Collections.Generic.IDictionary<string, object> sessionField;
        #endregion
        #region Properties
        /// <summary>
        /// The string builder that generation-time code is using to assemble generated output
        /// </summary>
        protected System.Text.StringBuilder GenerationEnvironment
        {
            get
            {
                if ((this.generationEnvironmentField == null))
                {
                    this.generationEnvironmentField = new global::System.Text.StringBuilder();
                }
                return this.generationEnvironmentField;
            }
            set
            {
                this.generationEnvironmentField = value;
            }
        }
        /// <summary>
        /// The error collection for the generation process
        /// </summary>
        public System.CodeDom.Compiler.CompilerErrorCollection Errors
        {
            get
            {
                if ((this.errorsField == null))
                {
                    this.errorsField = new global::System.CodeDom.Compiler.CompilerErrorCollection();
                }
                return this.errorsField;
            }
        }
        /// <summary>
        /// A list of the lengths of each indent that was added with PushIndent
        /// </summary>
        private System.Collections.Generic.List<int> indentLengths
        {
            get
            {
                if ((this.indentLengthsField == null))
                {
                    this.indentLengthsField = new global::System.Collections.Generic.List<int>();
                }
                return this.indentLengthsField;
            }
        }
        /// <summary>
        /// Gets the current indent we use when adding lines to the output
        /// </summary>
        public string CurrentIndent
        {
            get
            {
                return this.currentIndentField;
            }
        }
        /// <summary>
        /// Current transformation session
        /// </summary>
        public virtual global::System.Collections.Generic.IDictionary<string, object> Session
        {
            get
            {
                return this.sessionField;
            }
            set
            {
                this.sessionField = value;
            }
        }
        #endregion
        #region Transform-time helpers
        /// <summary>
        /// Write text directly into the generated output
        /// </summary>
        public void Write(string textToAppend)
        {
            if (string.IsNullOrEmpty(textToAppend))
            {
                return;
            }
            // If we're starting off, or if the previous text ended with a newline,
            // we have to append the current indent first.
            if (((this.GenerationEnvironment.Length == 0) 
                        || this.endsWithNewline))
            {
                this.GenerationEnvironment.Append(this.currentIndentField);
                this.endsWithNewline = false;
            }
            // Check if the current text ends with a newline
            if (textToAppend.EndsWith(global::System.Environment.NewLine, global::System.StringComparison.CurrentCulture))
            {
                this.endsWithNewline = true;
            }
            // This is an optimization. If the current indent is "", then we don't have to do any
            // of the more complex stuff further down.
            if ((this.currentIndentField.Length == 0))
            {
                this.GenerationEnvironment.Append(textToAppend);
                return;
            }
            // Everywhere there is a newline in the text, add an indent after it
            textToAppend = textToAppend.Replace(global::System.Environment.NewLine, (global::System.Environment.NewLine + this.currentIndentField));
            // If the text ends with a newline, then we should strip off the indent added at the very end
            // because the appropriate indent will be added when the next time Write() is called
            if (this.endsWithNewline)
            {
                this.GenerationEnvironment.Append(textToAppend, 0, (textToAppend.Length - this.currentIndentField.Length));
            }
            else
            {
                this.GenerationEnvironment.Append(textToAppend);
            }
        }
        /// <summary>
        /// Write text directly into the generated output
        /// </summary>
        public void WriteLine(string textToAppend)
        {
            this.Write(textToAppend);
            this.GenerationEnvironment.AppendLine();
            this.endsWithNewline = true;
        }
        /// <summary>
        /// Write formatted text directly into the generated output
        /// </summary>
        public void Write(string format, params object[] args)
        {
            this.Write(string.Format(global::System.Globalization.CultureInfo.CurrentCulture, format, args));
        }
        /// <summary>
        /// Write formatted text directly into the generated output
        /// </summary>
        public void WriteLine(string format, params object[] args)
        {
            this.WriteLine(string.Format(global::System.Globalization.CultureInfo.CurrentCulture, format, args));
        }
        /// <summary>
        /// Raise an error
        /// </summary>
        public void Error(string message)
        {
            System.CodeDom.Compiler.CompilerError error = new global::System.CodeDom.Compiler.CompilerError();
            error.ErrorText = message;
            this.Errors.Add(error);
        }
        /// <summary>
        /// Raise a warning
        /// </summary>
        public void Warning(string message)
        {
            System.CodeDom.Compiler.CompilerError error = new global::System.CodeDom.Compiler.CompilerError();
            error.ErrorText = message;
            error.IsWarning = true;
            this.Errors.Add(error);
        }
        /// <summary>
        /// Increase the indent
        /// </summary>
        public void PushIndent(string indent)
        {
            if ((indent == null))
            {
                throw new global::System.ArgumentNullException("indent");
            }
            this.currentIndentField = (this.currentIndentField + indent);
            this.indentLengths.Add(indent.Length);
        }
        /// <summary>
        /// Remove the last indent that was added with PushIndent
        /// </summary>
        public string PopIndent()
        {
            string returnValue = "";
            if ((this.indentLengths.Count > 0))
            {
                int indentLength = this.indentLengths[(this.indentLengths.Count - 1)];
                this.indentLengths.RemoveAt((this.indentLengths.Count - 1));
                if ((indentLength > 0))
                {
                    returnValue = this.currentIndentField.Substring((this.currentIndentField.Length - indentLength));
                    this.currentIndentField = this.currentIndentField.Remove((this.currentIndentField.Length - indentLength));
                }
            }
            return returnValue;
        }
        /// <summary>
        /// Remove any indentation
        /// </summary>
        public void ClearIndent()
        {
            this.indentLengths.Clear();
            this.currentIndentField = "";
        }
        #endregion
        #region ToString Helpers
        /// <summary>
        /// Utility class to produce culture-oriented representation of an object as a string.
        /// </summary>
        public class ToStringInstanceHelper
        {
            private System.IFormatProvider formatProviderField  = global::System.Globalization.CultureInfo.InvariantCulture;
            /// <summary>
            /// Gets or sets format provider to be used by ToStringWithCulture method.
            /// </summary>
            public System.IFormatProvider FormatProvider
            {
                get
                {
                    return this.formatProviderField ;
                }
                set
                {
                    if ((value != null))
                    {
                        this.formatProviderField  = value;
                    }
                }
            }
            /// <summary>
            /// This is called from the compile/run appdomain to convert objects within an expression block to a string
            /// </summary>
            public string ToStringWithCulture(object objectToConvert)
            {
                if ((objectToConvert == null))
                {
                    throw new global::System.ArgumentNullException("objectToConvert");
                }
                System.Type t = objectToConvert.GetType();
                System.Reflection.MethodInfo method = t.GetMethod("ToString", new System.Type[] {
                            typeof(System.IFormatProvider)});
                if ((method == null))
                {
                    return objectToConvert.ToString();
                }
                else
                {
                    return ((string)(method.Invoke(objectToConvert, new object[] {
                                this.formatProviderField })));
                }
            }
        }
        private ToStringInstanceHelper toStringHelperField = new ToStringInstanceHelper();
        public ToStringInstanceHelper ToStringHelper
        {
            get
            {
                return this.toStringHelperField;
            }
        }
        #endregion
    }
    #endregion
}
